export const CLCLN_BACNT_BANK_SE = [
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '2', cdDtlNm: '산업은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '3', cdDtlNm: '기업은헹' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '4', cdDtlNm: '국민은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '5', cdDtlNm: '외환은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '7', cdDtlNm: '수협' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '8', cdDtlNm: '수출입은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '11', cdDtlNm: '농협은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '12', cdDtlNm: '축협은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '20', cdDtlNm: '우리은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '23', cdDtlNm: 'SC제일은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '27', cdDtlNm: '씨티은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '31', cdDtlNm: '대구은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '32', cdDtlNm: '부산은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '34', cdDtlNm: '광주은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '35', cdDtlNm: '제주은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '37', cdDtlNm: '전북은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '39', cdDtlNm: '경남은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '45', cdDtlNm: '새마을금고' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '48', cdDtlNm: '신협' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '50', cdDtlNm: '상호저축은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '65', cdDtlNm: '대화은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '71', cdDtlNm: '우체국' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '81', cdDtlNm: '하나은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '88', cdDtlNm: '신한은행' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '89', cdDtlNm: '케이뱅크' },
  { cdSeId: 'CLCLN_BACNT_BANK_SE', cdDtlId: '90', cdDtlNm: '카카오뱅크' }
]
